# For activating client side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = '''
	accelerometer=(),
    ambient-light-sensor=(),
	autoplay=(),
    battery=(),
    camera=(),
	geolocation=(),
    gyroscope=(),
    magnetometer=(),
    microphone=(),
    midi=(),
    payment=(),
    picture-in-picture=(),
    publickey-credentials-get=(),
    usb=(),
    web-share=(self)'''
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.cloudfront.net; object-src 'none'; style-src 'self' https://*.cloudfront.net; img-src 'self' https://*.cloudfront.net https://*.unsplash.com; media-src 'none'; frame-src 'none'; font-src 'none'; connect-src 'self' https://*.cloudfront.net https://*.unsplash.com"