# For activating client side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = '''
	accelerometer=(),
    ambient-light-sensor=(),
	autoplay=(),
    battery=(),
    camera=(),
	geolocation=(),
    gyroscope=(),
    magnetometer=(),
    microphone=(),
    midi=(),
    payment=(),
    picture-in-picture=(),
    publickey-credentials-get=(),
    usb=(),
    web-share=(self)'''
    Content-Security-Policy = "default-src 'self'; script-src data: https://*.cloudfront.net; script-src-elem; script-src-attr; style-src 'self' data: https://*.cloudfront.net; style-src-elem; style-src-attr; img-src 'self' https://*.cloudfront.net; font-src; connect-src 'self' https://*.cloudfront.net; media-src 'self' https://*.cloudfront.net;  prefetch-src 'self' https://*.cloudfront.net https://*.cloudfront.net; worker-src 'self'; form-action 'self'; upgrade-insecure-requests; block-all-mixed-content;"
